name = "NeuralGraphPDE"
uuid = "dc0c328b-2f26-4c4e-a741-3d78bb01adf9"
authors = ["MilkshakeForReal <yicheng.wu@ucalgary.ca> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"

[compat]
Lux = "0.4"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
